motion_id = kick_0Hard

"kick used for kick selection
"Kick uses LeftFoot
"KickDistance:
"unlimited
"KickRange:
"ball.x < 220 &&  0< ball.y <60
"

label start

"HP HT  AL1 AL2 AL3AL4	AR1 AR2 AR3 AR4		LL0 LL1 LL2 LL3 LL4 LL5		LR0 LR1 LR2 LR3 LR4 LR5 Int Dur   
"stand
hardness 100 100 100 100 100 100 100 100 100 100 	100 100 100 100 100 100 100 100 100 100 100 100 500
0 -28 -90 30 0 0 -90 30 0 0		0 -1.8 -26 71 -45 1.8 	 	 0 -1.8 -26 71 -45 1.8			1 400
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

0 -28 -90 30 0 0 -90 30 0 0		0 -1.8 -30 60 -30 1.8 		 0 -1.8 -30 60 -30 1.8 			1 600
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

0 -28 -90 30 0 0 -90 30 0 0		0 -1.8 -30 60 -30 1.8 		 0 -1.8 -30 60 -30 1.8 			1 400
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

"now standing stable prepare Kick
0 -28 -90 30 0 0 -90 30 0 0		0 -25 -20 40 -20 25 	 0 25 -20 40 -20 -25		1 700
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

0 -28 -90 30 0 0 -90 30 0 0		0 -22 -50 100 -80 22	 0 22 -20 40 -20 -22 	 	1 200
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

0 -28 -20 30 0 0 -160 30 0 0	0 -20 -20 100 -60 30	 0 22 -20 40 -20 -22 	 	1 500
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

0 -28 -160 30 0 0 -20 30 0 0	0 -20 -80 20 15 30 	 	0 22 -20 40 -20 -22 		1 80
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

0 -28 -160 30 0 0 -20 30 0 0	0 -18 -80 20 50 30 		 0 22 -20 40 -20 -22 		1 40
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

0 -28 -90 30 0 0 -90 30 0 0	0 -30 -50 20 30 22 		 0 22 -20 40 -20 -22 		1 600
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start


0 -28 -90 30 0 0 -90 30 0 0	0 -34 -30 60 -30 22 	 0 22 -20 40 -20 -22 		1 400
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

"creating stable stand
* * -90 30 0 0 -90 30 0 0	0 -2 -30 60 -30 2 		 0 -2 -30 60 -30 2 			1 400
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

* * -90 30 0 0 -90 30 0 0	0 -1.8 -26 71 -45 1.8 	 0 -1.8 -26 71 -45 1.8		1 600
transition standUpFrontNao standUpFrontNao start
transition standUpBackNao standUpBackNao start

* * -90 30 0 0 -90 30 0 0	0 -1.8 -26 71 -45 1.8 	 0 -1.8 -26 71 -45 1.8		1 200                                                         
                         
transition allMotions extern start
