motion_id = pitch
"auf dem Nao schon getestet
label start

"HP HT  AL1 AL2 AL3 AL4 AR1 AR2 AR3 AR4 LL0 LL1 LL2 LL3 LL4 LL5 LR0 LR1 LR2 LR3 LR4 LR5 Int Dur   
 *  * 	-90 30 	0   0	-90 30  0   0	0   0 	0   0	0   0	0   0 	0   0	0   0	1   500

 *  * 	-90 30 	0   0	-90 30  0   0	0   0 	-30 0	10  0	0   0 	-30 0	10  0	1   1000
label stay
 *  * 	-90 30 	0   0	-90 30  0   0	0   0 	-30 0	10  0	0   0 	-30 0	10  0	1   500
transition pitch pitch stay
 *  * 	-90 30 	0   0	-90 30  0   0	0   0 	0   0	0   0	0   0 	0   0	0   0	1   1000


transition allMotions extern start
